# Estructuras de control básicas en Python

In [4]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
i = 0
while i < 10:
    print(i)
    i = i + 1

0
1
2
3
4
5
6
7
8
9


In [13]:
a = 70
b = 7
c = 1
if a < b  and a < c:
    print("a es el menor de todos los números")
elif b < a and b < c:
    print("b es el menor de todos los números")
else:
    print("c es el menor de todos los números")

c es el menor de todos los números


La clase anterior vimos comandos básicos de python, pero además tenemos varias librerías externas que nos ayudan a mejorar la eficiencia de nuestros cálculos en python.
Si nosotros queremos utilizar una librería externa para realizar cálculos más complejos, podemos importarla utilizando el comando "import"

In [15]:
#En general, numpy se encuentra pre cargada dentro de nuestro entorno de 
#python
import numpy #importar todas las funciones de python

In [16]:
#para utilizar las funciones o clases de numpy, vamos a escribir lo
#Siguiente:
# "nombre de la librería"."nombre de la función"
numpy.array([1,2,3])

array([1, 2, 3])

In [18]:
#También podemos re nombrar a una librería con un "alias", esto con el
#fin de no tener que escribir el nombre de la librería todo el tiempo.
#Ésto se efectúa de la siguiente forma:
# import "nombre de la librería" as "alias"

In [26]:
import numpy as np #alias estándar de numpy

In [27]:
np.array([1,2,3])

array([1, 2, 3])

In [30]:
#podemos importar la librería completa sin necesidad de escribir el 
#alias utilizando el caracter "*"
from numpy import *
#NO es recomendable, porque perdemos el seguimiento sobre qué
#librería se está utilizando para llamar a una función determinada

In [31]:
from numpy import *
from scipy import * #librería de métodos numéricos
from matplotlib import * #MATPLOTLIB se utiliza para graficar datos

In [34]:
import numpy as np
import scipy as scp
import matplotlib as mpl

In [37]:
#instalar paquetería utilizando el comando pip
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [40]:
#también podemos instalar paquetería desde anaconda utilizando el comando
#conda install "nombre del paquete"
pip install hmmlearn

     |████████████████████████████████| 129 kB 829 kB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [41]:
import hmmlearn

In [38]:
import sklearn

In [35]:
np.exp(0)

1.0

In [29]:
array([1,2,3])

array([1, 2, 3])

# Numpy

Numpy es una librería de cómputo científico que viene a solucionar los problemas que teníamos con las listas (operaciones vectoriales)

In [47]:
import numpy as np

#Crear arreglos de números
v1 = np.array([1,2,3,4,5])
l1 = [1,2,3,4,5]

In [61]:
#type(v1)

In [60]:
print(v1 + 3) #suma de un vector con un escalar
print([x + 3 for x in l1]) #suma de una lista con un escalar
print(v1 * 3) #producto de un vector con un escalar

[4 5 6 7 8]
[4, 5, 6, 7, 8]
[ 3  6  9 12 15]


In [58]:
v2 = np.array([5,6,7,8,9])

In [62]:
#Podemos realizar operaciones con dos vectores
print(v1+v2)
print(v1*v2)

[ 6  8 10 12 14]
[ 5 12 21 32 45]


In [68]:
#existen funciones especiales como funciones trigonométricas, logarít-
#micas y exponenciales
print(np.exp(v1))
print(np.log(v1)) # en lenguajes de programación "log" se refiere al 
#logaritmo natural
#np.log()# SI NECESITAN AYUDA PARA SABER LOS ARGUMENTOS QUE LLEVA UNA FUNCIÓN,
#OPRIMIR MAYUSC+TAB
print(np.sin(v1)) #seno elemento a elemento de un arreglo

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [70]:
#Versión instalada de numpy
np.__version__

'1.19.5'

In [72]:
#Operaciones matriciales
#Definir una matriz
m1 = np.array([[1,2,4],[5,7,9],[20,3,6]])
print(m1)

[[ 1  2  4]
 [ 5  7  9]
 [20  3  6]]


In [74]:
#el comando shape, nos dice las dimensiones de una matriz
print(m1.shape)
type(m1)


(3, 3)


numpy.ndarray

In [94]:
#Acceder al tercer renglón de la matriz
m1[2][2]

6

In [85]:
#Acceder a la tercera columna de la matriz
m1[:,2]

array([4, 9, 6])

In [95]:
#Operaciones con matrices
m1 = np.array([[1,2,4],[5,7,9],[20,3,6]])
m2 = np.array([[1,2,3],[5,8,9],[20,11,6]])

In [98]:
print(m1+m2) #suma de dos matrices
print(m1*m2) #producto de dos matrices
print(m1.dot(m2)) #producto matricial de dos matrices

[[ 2  4  7]
 [10 15 18]
 [40 14 12]]
[[  1   4  12]
 [ 25  56  81]
 [400  33  36]]
[[ 91  62  45]
 [220 165 132]
 [155 130 123]]


In [99]:
m3 = np.linalg.inv(m1) #inversa de una matriz

In [102]:
m3.dot(m1) #Matriz identidad a partir de una matriz y su inversa

array([[ 1.00000000e+00,  5.55111512e-17,  5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17, -2.18575158e-16,  1.00000000e+00]])

In [111]:
m2 = np.array([[1,2,3],[5,8,9],[20,11,6]])
m4 = np.matrix([[1,2,3],[5,8,9],[20,11,6]])

In [112]:
m4.dot(m2)

matrix([[ 71,  51,  39],
        [225, 173, 141],
        [195, 194, 195]])

In [107]:
type(m3)

numpy.ndarray